#!/bin/bash

# this script exists to test different serial port possibilities for ACM[0-1]

/home/$USER/mav/mavconn/build/bin/mavconn-bridge-serial -v -d -p /dev/ttyAMA0 --pc2serial || /home/$USER/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyAMA1 --pc2serial || /home/$USER/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyAMA2 --pc2serial || /home/$USER/mav/mavconn/build/bin/mavconn-bridge-serial -p /dev/ttyAMA99 --pc2serial
